[package]
name = "marpa-derives"
description = "Compile-time BNF to Marpa Grammar builder"
version = "0.0.1"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
regex = "1.1.0"
syn = "0.15"
proc-macro2 = "0.4"
quote = "0.6"
lazy_static = "1.0.0"
marpa = {version = "0.3.0", path="../marpa"}
