use std::env;
use std::fs::{self, File};
use std::io;
use std::path::{Path, PathBuf};

use bindgen::builder;
use flate2::read::GzDecoder;
use tar::Archive;

const LIBMARPA_VERSION: &str = "8.6.2";

// The full library per the tarball's Makefile.am `libmarpa_la_SOURCES`
// (Makefile.win32's shorter list predates marpa_tavl/marpa_codes).
const LIBMARPA_SOURCES: [&str; 6] = [
    "marpa.c",
    "marpa_obs.c",
    "marpa_avl.c",
    "marpa_tavl.c",
    "marpa_ami.c",
    "marpa_codes.c",
];

fn crate_root() -> PathBuf {
    env::var("CARGO_MANIFEST_DIR").unwrap().into()
}
fn out_dir() -> PathBuf {
    env::var("OUT_DIR").unwrap().into()
}

fn main() {
    let path = extract_libmarpa(LIBMARPA_VERSION).unwrap();
    build_libmarpa(&path).unwrap();
    run_bindgen(&path).unwrap();
}

// extract a tarball at `path` into `out_dir`
//
// borrowed from the rust cookbook: https://rust-lang-nursery.github.io/rust-cookbook/compression/tar.html
fn extract_tar_gz<P, Q>(path: P, out_dir: Q) -> io::Result<()>
where
    P: AsRef<Path>,
    Q: AsRef<Path>,
{
    let tar_gz = File::open(path)?;
    let tar = GzDecoder::new(tar_gz);
    let mut archive = Archive::new(tar);
    archive.unpack(out_dir)
}

// extract a libmarpa tarball with the provided version. Returns the extracted
// libmarpa directory.
//
// Assumes that there's a libmarpa-VERSION.tar.gz in the crate root
fn extract_libmarpa(version: &'static str) -> io::Result<PathBuf> {
    let out = out_dir();
    let libmarpa_name = format!("libmarpa-{version}");
    let libmarpa_tarball = crate_root().join(format!("{libmarpa_name}.tar.gz"));
    println!("cargo:rerun-if-changed={}", libmarpa_tarball.display());
    extract_tar_gz(libmarpa_tarball, &out)?;
    Ok(out.join(libmarpa_name))
}

// Synthesize the `config.h` that the libmarpa sources `#include`.
//
// The dist tarball ships every generated source already, so autoconf's
// only real output here was config.h — and of its whole macro set
// (HAVE_* header probes, SIZEOF_INT, PACKAGE_*), the only macros the
// sources actually consume are MARPA_LIB_{MAJOR,MINOR,MICRO}_VERSION:
// marpa.c's compile-time cross-check against marpa.h's
// MARPA_{MAJOR,MINOR,MICRO}_VERSION, plus the marpa_*_version runtime
// constants. Derive them from the tarball's LIB_VERSION file so a
// future tarball bump can't drift.
fn write_config_h<P: AsRef<Path>>(path: P) -> io::Result<()> {
    let path = path.as_ref();
    let lib_version = fs::read_to_string(path.join("LIB_VERSION"))?;
    let mut parts = lib_version.trim().split('.');
    let mut next = || {
        parts
            .next()
            .and_then(|p| p.parse::<u32>().ok())
            .ok_or_else(|| io::Error::other(format!("malformed LIB_VERSION: {lib_version:?}")))
    };
    let (major, minor, micro) = (next()?, next()?, next()?);
    fs::write(
        path.join("config.h"),
        format!(
            "/* Generated by libmarpa-sys build.rs from LIB_VERSION — see build.rs */\n\
             #define MARPA_LIB_MAJOR_VERSION {major}\n\
             #define MARPA_LIB_MINOR_VERSION {minor}\n\
             #define MARPA_LIB_MICRO_VERSION {micro}\n"
        ),
    )
}

// build the extracted libmarpa at the given path
//
// Uses the `cc` crate instead of the tarball's `./configure && make`:
// configure needs a Unix shell + make, which do not exist on native
// Windows (MSVC), while `cc` drives each platform's own compiler
// (cl.exe on windows-msvc, cc/clang elsewhere) and emits the
// cargo:rustc-link-{search,lib} metadata itself.
fn build_libmarpa<P: AsRef<Path>>(path: P) -> io::Result<()> {
    let path = path.as_ref();
    write_config_h(path)?;
    cc::Build::new()
        .files(LIBMARPA_SOURCES.iter().map(|f| path.join(f)))
        .include(path)
        // The previous configure invocation forced CFLAGS="-fPIC -O3"
        // regardless of cargo profile; keep libmarpa at full optimization
        // even in debug/test builds — the parser dominates math-parse time
        // and is not what anyone is stepping through with a debugger.
        .opt_level(3)
        .pic(true)
        // libmarpa is C99 that predates MSVC warning hygiene; its warnings
        // are upstream's business, not this build's.
        .warnings(false)
        .compile("marpa");
    Ok(())
}

// run bindgen on the extracted libmarpa at the given path
//
// assumes that there's a 'marpa.h' in the provided directory
fn run_bindgen<P>(path: P) -> io::Result<()>
where
    P: AsRef<Path>,
{
    let bindings = builder()
        .header(format!("{}", path.as_ref().join("marpa.h").display()))
        .blocklist_type("max_align_t")
        .generate()
        .map_err(|_| io::Error::other("failed to generate bindings"))?;

    bindings.write_to_file(out_dir().join("raw.rs"))
}
